spring:
  redis:
    host: localhost
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    local-redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 16
          max-wait: 100
          max-idle: 8
          min-idle: 4
